### PR TITLE
Thorns sprites (reopen)

### PR DESCRIPTION
**Pull request by Rvtar**
I remade my fork so I could have a base branch, synced to main, to make my branches out of.

Same sprites as the old PR, the current sprites looked the same, thorn colors correspond to their token ranks.

### CODE REVIEW

**Comment by Sense101** [comment]
I like this - however, I'm unsure if it would be better to have the sprites match their armor alternatives rather than the token cost, as that can change. So the order would then be iron, diamond, netherite. Any thoughts on this?

**Comment by Rvtar** [comment]
I did realize that quickly after I finished the sprites so I decided to see if someone would say the same thing. I will update them to be iron-diamond-netherite.

**Comment by Rvtar** [comment]
Should I also make the sprites 16×16?

**Comment by Sense101** [comment]
Looks good - congrats on your first PR!

**Comment by Sense101** [comment]
I just saw  this "How too make iron not resemble paper."
Are you happy with how it looks now?

**Comment by Benji42** [comment]
i think it'd look pretty good for iron to just have the normal black spikes, it was the original thorns after all

**Comment by Rvtar** [comment]
> i think it'd look pretty good for iron to just have the normal black spikes, it was the original thorns after all

The issue would be the resemblance to Netherite.

**Comment by Rvtar** [comment]
> I just saw this "How too make iron not resemble paper." Are you happy with how it looks now?

I am.

**Pull request merged**
