### PR TITLE
Ladder

### PR DESCRIPTION
**Pull request by NikoUY**
Needs #182 to work.

### CODE REVIEW

**Comment by Sense101** [comment]
I changed onApply so it no longer returns done or invalid, as it's now more universal for all cards.

**Comment by Sense101** [comment]
for clarity on the canAttach return options, please see the original method - you should be returning invalid if the slot doesn't match

**Comment by NikoUY** [comment]
I think it's good now

**Comment by Sense101** [comment]
please update canAttach

**Comment by NikoUY** [comment]
Done

**Pull request merged**
