### PR TITLE
Improve Battle Log entries

### PR DESCRIPTION
**Pull request by Screaper91**
- Adds entries for reviving a hermit with Totem and "Deathloop".
- Allows hermit attack entries to be edited before being sent in chat.

### CODE REVIEW

**Comment by Benji42** [comment]
Do you think we could move over coinflips to use `modifyHermitAttackDescription` as well? It would be more compact.

**Comment by Screaper91** [comment]
I would create a new function to add the coin flips to an entry since we want the result to be shown after the animation plays.
Other scenarios to consider:
- "Sheep Stare" and "Watch This" may flip again after the first flip is heads
- "Trap Hole" flips for each single-use played (Piston, Fire Charge, and "Geminislay" allow multiple to played in one turn)
- "Aussie Ping", "Sheep Stare", and "Trap Hole" flip during the opponent's turn

**Comment by Benji42** [comment]
in that case this looks good. i don't think we need to worry about modifying the coinflip system immediately.

**Review by Benji42 — COMMENTED** [review]
I don't like how `modifyHermitAttackDescription` and `modifyHermitAttackTarget` work. We shouldn't have to mutate battle log entries after they're created.

**Comment by Benji42** [comment]
I decided to rework this system myself since there's a lot to be changed.

however, you can take a shot too if you'd like

**Comment by Benji42** [comment]
Superseded by #538

**Pull request closed without merging**
